'use strict';

function escapeHTML(value) {
  return String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
function heading(title, lead) {
  return `<h2>${title}</h2><p class="intro">${lead}</p>`;
}
function officialLink(name) {
  return `<a href="${tools[name].url}" target="_blank" rel="noopener noreferrer">وب‌سایت رسمی ↗</a>`;
}
const usageExamples = {
  Perplexity: 'مقایسه ابزار مستندسازی با معیارهای SSO، export و API.',
  NotebookLM: 'استخراج تصمیم‌ها و اختلاف‌ها از سه گزارش داخلی.',
  Elicit: 'بررسی شواهد اثر AI بر بهره‌وری توسعه‌دهندگان.',
  Claude: 'تبدیل یادداشت‌های پراکنده به RFC با trade-offها.',
  Grammarly: 'بازنویسی ایمیل انگلیسی با درخواست اقدام روشن.',
  'Notion AI': 'استخراج تصمیم، اقدام و مسئول از صورت‌جلسه.',
  ChatGPT: 'دسته‌بندی تیکت‌ها و بررسی روند هفتگی از CSV.',
  'Julius AI': 'مقایسه median و p90 زمان پاسخ بین دسته‌ها.',
  Gemini: 'توضیح روند نمودار و مشخص کردن داده‌های لازم.',
  'Adobe Firefly': 'پس‌زمینه رویداد با پالت برند و فضای خالی برای عنوان.',
  Midjourney: 'چند جهت بصری اولیه برای تصویر یک کمپین.',
  Canva: 'تبدیل گزارش تصمیم به ارائه پنج‌صفحه‌ای.',
  Runway: 'تبدیل تصویر محصول به یک شات کوتاه با حرکت دوربین.',
  Sora: 'نمونه اولیه یک صحنه برای معرفی یا کمپین.',
  ElevenLabs: 'روایت متن معرفی یک ویژگی با صدای مجاز.',
  Whisper: 'تبدیل صوت مصاحبه کاربر به متن قابل جستجو.',
  Descript: 'حذف بخش‌های تکراری مصاحبه از روی متن.',
  n8n: 'بازخورد جدید → دسته‌بندی → ثبت → اعلان تیم.',
  Zapier: 'ایمیل جدید → خلاصه → ساخت task.',
  Make: 'تیکت جدید → تشخیص موضوع → هدایت به صف مرتبط.',
  'OpenAI API': 'خلاصه و موضوع تیکت به شکل JSON در پنل.',
  'Anthropic API': 'استخراج تصمیم و اقدام از متن گزارش.',
  'Gemini API': 'تحلیل هم‌زمان متن درخواست و تصویر خطا.',
  Dify: 'نمونه اولیه دستیار پاسخ‌گویی از مستندات محصول.',
  LlamaIndex: 'بازیابی بخش مرتبط سند و پاسخ با منبع در محصول.'
};
function practicalCards(names) {
  return `<div class="practical-grid ${names.length===2?'two':''}">${names.map(name => {
    const t = tools[name];
    return `<article class="practical-card"><div class="tool-card-header">${toolMark(name)}<h3>${name}</h3><button class="tool-info" data-tool="${name}" aria-label="جزئیات ${name}">↗</button></div><p class="tool-description">${t.what}</p><h4>کِی به کار می‌آید؟</h4><p>${t.when}</p><h4>چطور شروع کنیم؟</h4><p>${t.start}</p><div class="work-example"><h4>نمونه در کار تیم</h4><p>${usageExamples[name] || t.prompt}</p></div><div class="practical-footer">${officialLink(name)}<button data-copy-tool="${name}">کپی نمونه درخواست</button></div></article>`;
  }).join('')}</div>`;
}
function universeArt() {
  const nodes = [['code','Coding',6,90],['research','Research',250,60],['design','Design',295,204],['agent','Agents',236,350],['automation','Automation',2,324],['voice','Voice',0,220]];
  return `<div class="universe-art" aria-label="کاربردهای مختلف AI"><svg viewBox="0 0 445 470" aria-hidden="true"><ellipse class="orbit-line" cx="223" cy="244" rx="178" ry="183"/><ellipse class="orbit-line" cx="223" cy="244" rx="121" ry="128"/>${nodes.map(n=>`<path class="branch-line" d="M223 244 L${n[2]+65} ${n[3]+24}"/>`).join('')}</svg><div class="world-core"><strong>AI</strong><small>BEYOND CHAT</small></div>${nodes.map((n,i)=>`<div class="world-satellite" style="left:${n[2]}px;top:${n[3]}px;--i:${i}">${icon(n[0])}<strong>${n[1]}</strong></div>`).join('')}<div class="world-caption">RESEARCH <span>→ BUILD → AUTOMATE</span></div></div>`;
}

const codingContexts = {
  Antigravity: ['محیط توسعه با Agent', 'پیاده‌سازی و بررسی UI', ['باز کردن پروژه و تعریف رفتار', 'بررسی فایل‌ها و پیاده‌سازی', 'اجرای برنامه و بررسی در مرورگر', 'بازبینی تغییرات و رفتار نهایی']],
  'Claude Code': ['Agent در جریان توسعه', 'رفع باگ و تغییر چندفایلی', ['اجرای ابزار در پروژه', 'ردیابی مسیر خطا', 'اصلاح حداقلی و اجرای بررسی‌ها', 'توضیح diff و نتیجه']],
  Codex: ['Agent برای task توسعه', 'یک تغییر با معیار پذیرش مشخص', ['اتصال پروژه و شرح task', 'بررسی کد مرتبط', 'اعمال تغییر و اجرای بررسی', 'تحویل خلاصه و diff']],
  OpenCode: ['Agent متن‌باز و چندارائه‌دهنده‌ای', 'کار با مدل انتخابی در مخزن', ['انتخاب مدل و ارائه‌دهنده', 'دادن context پروژه و مسئله', 'تغییر فایل‌ها و اجرای ابزار', 'بررسی نتیجه و diff']],
  Codera: ['دسکتاپ و ترمینال کوئرا', 'پیاده‌سازی و رفع باگ', ['باز کردن پروژه', 'انتخاب مدل مناسب کار', 'درخواست تغییر مشخص', 'بررسی تغییرات و نتیجه']],
  Cursor: ['ویرایشگر کد مجهز به AI', 'کمک روزمره نزدیک به فایل‌ها', ['باز کردن مخزن در ادیتور', 'انتخاب فایل و context', 'درخواست تغییر با حفظ رفتار', 'بررسی و پذیرفتن diff']]
};
function codingSlide(name) {
  const t = tools[name], c = codingContexts[name];
  return `${heading(`<span class="accent">${name}</span> · ${c[0]}`, t.what)}<div class="coding-showcase workplace-showcase"><div class="showcase-copy"><div class="showcase-heading">${toolMark(name,true)}<div><h3>${name}</h3><small>${identities[name][3]}</small></div></div><h4>کار مناسب</h4><p>${t.when}</p><h4>شروع استفاده</h4><p>${t.start}</p><div class="example"><h4>درخواست قابل استفاده در یک پروژه</h4><p>${t.prompt}</p></div><div class="showcase-links"><button class="primary" data-copy-tool="${name}">کپی نمونه درخواست</button>${officialLink(name)}</div></div><div class="editor-demo"><div class="editor-topbar"><span class="editor-dot"></span><span class="editor-dot"></span><span class="editor-dot"></span><span>EXAMPLE WORKFLOW / ${name.toUpperCase()}</span></div><div class="editor-content"><div class="editor-path">TASK → IMPLEMENTATION → REVIEW</div><div class="coding-route">${c[2].map((step,i)=>`<div><span>0${i+1}</span><p>${step}</p></div>`).join('')}</div><div class="expected-output"><strong>خروجی مورد انتظار</strong><p>تغییر در پروژه، نتیجه بررسی و توضیحی که بتوانید روی آن تصمیم بگیرید.</p></div></div><span class="editor-badge">ILLUSTRATIVE WORKFLOW · NOT A LIVE RUN</span></div></div>`;
}

const workflow = [
  ['Research', 'Perplexity / Elicit', 'پیدا کردن گزینه‌ها و منابع رسمی', 'فهرست گزینه‌ها + لینک منبع'],
  ['Analyze', 'NotebookLM / Claude', 'مقایسه بر اساس معیارهای تیم', 'جدول مقایسه + موارد نامشخص'],
  ['Write', 'Claude / Notion AI', 'نوشتن گزارش تصمیم برای همکاران', 'پیش‌نویس گزارش + trade-offها'],
  ['Visuals', 'Canva / Firefly', 'ساخت نمودار و تصویر مرتبط', 'جدول یا Visual برای پیام اصلی'],
  ['Presentation', 'Canva / Codera / Codex', 'ساخت ارائه یا خروجی وب', 'نسخه قابل ارائه به تیم'],
  ['Review', 'Human + AI', 'بررسی ادعا، منبع و نتیجه', 'نسخه نهایی + اقدام بعدی']
];

const previousSlides = [
  {id:'cover', title:'AI فقط Chatbot نیست', kicker:'AI CLUB / QUERA', cover:true, render:()=>`<div class="cover"><div><div class="eyebrow">01 / AI CLUB — QUERA</div><h1>AI فقط<br><span class="hero-english">Chatbot</span> نیست!</h1><p class="hero-lead">کاربردهای عملی AI در تحقیق، توسعه<br>و کارهای روزمره تیم.</p><div class="cover-credit"><img src="assets/quera-logo.svg" alt="Quera"><span>ارائه داخلی برای همکاران · AI Club</span></div></div>${universeArt()}</div><span class="cover-note">CAPABILITIES. TOOLS. PRACTICAL STARTING POINTS.</span>`},
  {id:'agenda', title:'هدف و مسیر جلسه', kicker:'WHY THIS SESSION', render:()=>`${heading('یک کاربرد پیدا کنیم که <span class="accent">در کارمان قابل استفاده باشد.</span>', 'مرور قابلیت‌های موجود، ابزارهای مرتبط و نقطه شروع استفاده؛ با مثال‌های کاری.') }<div class="brief-grid"><article>${icon('research')}<h3>چه کارهایی ممکن است؟</h3><p>از تحلیل مستندات و داده تا تغییر کد، تولید محتوا و اتوماسیون.</p></article><article>${icon('terminal')}<h3>چطور شروع کنیم؟</h3><p>برای هر حوزه یک ابزار، ورودی مناسب و نمونه درخواست مشخص می‌بینیم.</p></article><article>${icon('check')}<h3>چه چیزی با خودمان ببریم؟</h3><p>یک کار واقعی و محدود که بتوانیم بعد از جلسه با یکی از ابزارها امتحان کنیم.</p></article></div><div class="insight">معیار انتخاب: <strong class="accent">نوع کار و خروجی موردنیاز</strong>؛ نه صرفاً نام مدل یا ابزار.</div>`},
  {id:'landscape', title:'مرور کاربردها در کار تیمی', kicker:'AI AT WORK', render:()=>`${heading('AI در کار تیمی؛ <span class="accent">چهار گروه کاربرد.</span>', 'انتخاب ابزار را بر اساس نوع کار، ورودی در دسترس و خروجی موردنیاز انجام می‌دهیم.')}<div class="capability-grid"><article>${icon('research')}<h3>تحقیق و کار با دانش</h3><p>پیدا کردن منابع، خلاصه اسناد و تحلیل داده.</p><div class="capability-tags">Research · Knowledge / RAG · Data</div></article><article>${icon('code')}<h3>توسعه نرم‌افزار</h3><p>فهم مخزن، رفع باگ و پیاده‌سازی با ابزارهای توسعه.</p><div class="capability-tags">Coding · Agents · AI + APIs</div></article><article>${icon('design')}<h3>تولید و ویرایش محتوا</h3><p>نوشتن، طراحی، ساخت ویدئو و کار با صوت.</p><div class="capability-tags">Writing · Design · Video · Voice</div></article><article>${icon('automation')}<h3>هماهنگی و اجرای فرایند</h3><p>اتصال سرویس‌ها و خودکارسازی کارهای تکراری.</p><div class="capability-tags">Automation · Chat</div></article></div>`},
  {id:'research', title:'تحقیق و فهم مستندات', kicker:'RESEARCH / KNOWLEDGE', render:()=>`${heading('تحقیق و مستندات؛ <span class="accent">از جستجو تا فهم منابع.</span>', 'برای مقایسه ابزارها، مرور گزارش‌ها یا پیدا کردن پشتوانه یک تصمیم.')}${practicalCards(['Perplexity','NotebookLM','Elicit'])}`},
  {id:'writing', title:'نوشتن و مستندسازی', kicker:'WRITING / DOCUMENTATION', render:()=>`${heading('نوشتن؛ <span class="accent">از یادداشت خام تا سند کاری.</span>', 'مخاطب، قالب و اطلاعات ورودی را مشخص کنید؛ پیش‌نویس را در جریان کار خودتان بازبینی کنید.')}${practicalCards(['Claude','Grammarly','Notion AI'])}`},
  {id:'data', title:'تحلیل داده‌های تیم', kicker:'DATA / ANALYSIS', render:()=>`${heading('داده؛ <span class="accent">پرسش از فایل، نمودار و گزارش.</span>', 'برای تحلیل اولیه CSV و پیدا کردن الگوهایی که ارزش بررسی بیشتر دارند.')}${practicalCards(['ChatGPT','Julius AI','Gemini'])}`},
  {id:'coding', title:'انتخاب ابزار کدنویسی', kicker:'CODING TOOLS', render:()=>`${heading('ابزارهای کدنویسی؛ <span class="accent">کدام محیط به کارمان نزدیک‌تر است؟</span>', 'این‌ها ابزار و محیط کارند؛ مدل، یکی از اجزایی است که پشت آن‌ها قرار می‌گیرد.')}<div class="coding-comparison">${codingTools.map(n=>`<article><div class="tool-card-header">${toolMark(n)}<h3>${n}</h3></div><strong>${codingContexts[n][0]}</strong><p>${codingContexts[n][1]}</p><a href="${tools[n].url}" target="_blank" rel="noopener noreferrer">وب‌سایت رسمی ↗</a></article>`).join('')}</div><p class="section-note">با یک تغییر محدود شروع کنید؛ رفتار مورد انتظار و معیار پذیرش را در درخواست بنویسید.</p>`},
  ...['Antigravity','Claude Code','Codex','OpenCode'].map(name=>({id:`coding-${name.toLowerCase().replace(/\s/g,'-')}`, title:`معرفی ${name}`, kicker:`CODING / ${name.toUpperCase()}`, render:()=>codingSlide(name)})),
  {id:'codera', title:'معرفی کدرا', kicker:'CODING / CODERA — QUERA', render:()=>`${heading('کدرا؛ <span class="accent">کار روی پروژه در دسکتاپ و ترمینال.</span>', 'دستیار برنامه‌نویسی کوئرا برای پرسیدن درباره کد، پیاده‌سازی و رفع باگ.')}<div class="codera-layout"><div class="codera-copy"><div class="codera-feature">${icon('layers')}<div><h3>مدل را متناسب با کار انتخاب کنید</h3><p>نوع درخواست و پیچیدگی پروژه، مبنای انتخاب مدل است.</p></div></div><div class="codera-feature">${icon('terminal')}<div><h3>یک درخواست محدود و مشخص بدهید</h3><p>پروژه را باز کنید؛ رفتار مورد انتظار، فایل‌های مرتبط و معیار پذیرش را مشخص کنید.</p></div></div><div class="codera-feature">${icon('check')}<div><h3>تغییرات را بررسی کنید</h3><p>diff و نتیجه بررسی را ببینید و درباره پذیرفتن تغییر تصمیم بگیرید.</p></div></div></div><figure class="codera-screenshot" style="margin:0"><img src="assets/codera-desktop.webp" alt="تصویر رسمی محیط دسکتاپ کدرا" width="1920" height="1080"><figcaption class="codera-caption"><span>تصویر واقعی محصول · وب‌سایت رسمی کوئرا</span><span>CODERA / DESKTOP</span></figcaption></figure></div><div class="codera-footer"><button class="primary" data-copy-tool="Codera">کپی نمونه درخواست</button><p class="section-note">مثال: پیاده‌سازی یک صفحه با حالت‌های loading، empty و error مطابق الگوهای پروژه.</p>${officialLink('Codera')}</div>`},
  {id:'coding-cursor', title:'معرفی Cursor', kicker:'CODING / CURSOR', render:()=>codingSlide('Cursor')},
  {id:'design', title:'طراحی و تولید تصویر', kicker:'DESIGN / IMAGE', render:()=>`${heading('طراحی؛ <span class="accent">دارایی بصری و نمونه اولیه.</span>', 'برای کمپین، ارائه یا محتوای محصول؛ سبک برند و کاربرد تصویر را در ورودی مشخص کنید.')}${practicalCards(['Adobe Firefly','Midjourney','Canva'])}`},
  {id:'video', title:'تولید ویدئو', kicker:'VIDEO / PROTOTYPING', render:()=>`${heading('ویدئو؛ <span class="accent">از ایده تا شات اولیه.</span>', 'برای نمونه‌سازی ایده و ساخت شات کوتاه؛ نه لزوماً تولید یک ویدئوی کامل در یک درخواست.')}${practicalCards(['Runway','Sora'])}<p class="section-note">ورودی مفید: موضوع صحنه + تصویر مرجع + حرکت دوربین + مدت. خروجی: چند شات منتخب برای ویرایش. دسترسی به قابلیت‌ها ممکن است به پلن یا منطقه وابسته باشد.</p>`},
  {id:'voice', title:'گفتار، متن و ویرایش صوت', kicker:'VOICE / SPEECH', render:()=>`${heading('صوت؛ <span class="accent">تولید گفتار و تبدیل جلسه به متن.</span>', 'برای مصاحبه کاربر، ویدئوی آموزشی یا روایت یک ویژگی محصول.')}${practicalCards(['ElevenLabs','Whisper','Descript'])}`},
  {id:'automation', title:'اتوماسیون کارهای تکراری', kicker:'AUTOMATION / INTEGRATIONS', render:()=>`${heading('اتوماسیون؛ <span class="accent">AI بین ابزارهای فعلی تیم.</span>', 'اگر کاری trigger، ورودی و مقصد مشخص دارد، می‌توان آن را به یک Workflow تبدیل کرد.')}${practicalCards(['n8n','Zapier','Make'])}`},
  {id:'apis', title:'AI داخل محصول', kicker:'AI + APIS', render:()=>`${heading('API؛ <span class="accent">اضافه کردن یک قابلیت AI به محصول.</span>', 'مثال مشترک: دریافت متن تیکت و نمایش خلاصه و موضوع آن در پنل پشتیبانی.')}${practicalCards(['OpenAI API','Anthropic API','Gemini API'])}`},
  {id:'rag', title:'پاسخ با تکیه بر دانش تیم', kicker:'KNOWLEDGE / RAG', render:()=>`${heading('RAG؛ <span class="accent">پاسخ بر اساس اسناد مرتبط.</span>', 'به‌جای تکیه صرف بر دانش مدل، متن مرتبط از منابع خودمان وارد پاسخ‌سازی می‌شود.')}${practicalCards(['NotebookLM','Dify','LlamaIndex'])}`},
  {id:'agents', title:'Chatbot و Agent در یک کار واقعی', kicker:'CHATBOT / AGENT', render:()=>`${heading('Chatbot و Agent؛ <span class="accent">تفاوت در اجرای کار است.</span>', 'یک درخواست مشترک: «ابزارهای مستندسازی را طبق معیارهای تیم مقایسه کن.»')}<div class="flow-columns workplace-flows"><div class="flow-column"><h3>Chatbot</h3>${['دریافت سؤال و context','تهیه پاسخ یا پیش‌نویس','ادامه تحقیق و اجرا توسط شما'].map((s,i)=>`<div class="flow-node chatbot-node lit">${s}</div>${i<2?'<div class="flow-arrow">↓</div>':''}`).join('')}<p>مناسب برای فکر کردن، نوشتن و تحلیل با context مشخص.</p></div><div class="flow-column"><h3>Agent</h3>${['تعریف هدف و معیار خروجی','برنامه‌ریزی مراحل','استفاده از Search / Browse / Code','بررسی منابع و نتیجه','تهیه خروجی برای بازبینی'].map((s,i)=>`<div class="flow-node agent-node lit">${s}</div>${i<4?'<div class="flow-arrow">↓</div>':''}`).join('')}<p>با ابزارهای در دسترس، بخشی از مراحل را اجرا می‌کند.</p></div></div><div class="agent-controls"><button id="agent-play">نمایش توالی اجرا</button><span id="agent-status" class="section-note" aria-live="polite">نمونه‌ها: Coding Agents برای پروژه؛ Manus برای بعضی کارهای چندمرحله‌ای.</span></div>`},
  {id:'workflow', title:'Workflow تحقیق تا ارائه', kicker:'WORKFLOW / TEAM DECISION', render:()=>`${heading('یک Workflow کاری؛ <span class="accent">از تحقیق تا گزارش تصمیم.</span>', 'سناریو: انتخاب یک ابزار مستندسازی برای تیم و ارائه نتیجه به همکاران.')}<div class="workflow-board">${workflow.map((s,i)=>`<article><span class="workflow-number">0${i+1} / ${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p><div>${icon('arrow')} ${s[3]}</div></article>`).join('')}</div><p class="section-note">همه مراحل لزوماً ابزار جداگانه نمی‌خواهند. هدف، اتصال خروجی‌ها و کاهش کار دستی بین مرحله‌هاست.</p>`},
  {id:'demo', title:'نمونه ورودی و خروجی Workflow', kicker:'WORKED EXAMPLE / OFFLINE', render:()=>`${heading('نمونه اجرا؛ <span class="accent">چه ورودی بدهیم، چه خروجی بگیریم؟</span>', 'پیش‌نمایش آفلاین مراحل؛ جستجو و اجرای مدل در این صفحه انجام نمی‌شود.')}<div class="demo-layout"><div class="demo-controls card"><label for="demo-topic">کار موردنظر</label><input id="demo-topic" value="انتخاب ابزار مستندسازی تیم" maxlength="90"><p>معیارهای نمونه: جستجو، export، API و SSO.<br>خروجی هدف: جدول مقایسه و گزارش تصمیم.</p><div class="demo-stage-list">${workflow.map((s,i)=>`<button data-demo-stage="${i}" aria-pressed="${i===0}">${i+1}. ${s[0]}</button>`).join('')}</div></div><div class="demo-log" id="demo-log" aria-live="polite"></div></div>`},
  {id:'start', title:'نقطه شروع استفاده', kicker:'A PRACTICAL START', render:()=>`${heading('برای شروع، <span class="accent">یک کار کوچک از همین هفته.</span>', 'ابزار را به مسئله فعلی وصل کنیم؛ از یک خروجی محدود شروع کنیم.')}<div class="starting-grid"><article>${icon('research')}<h3>تحقیق یا فهم سند</h3><p>یک مقایسه واقعی یا سه گزارش مرتبط انتخاب کنید.</p><strong>Perplexity / NotebookLM</strong><span>خروجی: جدول مقایسه یا خلاصه مستند</span></article><article>${icon('code')}<h3>توسعه نرم‌افزار</h3><p>یک باگ یا تغییر کوچک با معیار پذیرش روشن.</p><strong>Codera / Claude Code / Codex</strong><span>خروجی: diff و نتیجه بررسی</span></article><article>${icon('automation')}<h3>کار تکراری تیم</h3><p>یک trigger و یک مقصد مشخص؛ مثل فرم به جدول.</p><strong>n8n / Make / Zapier</strong><span>خروجی: Workflow قابل اجرای مجدد</span></article></div><div class="insight">بعد از امتحان: <strong class="accent">کیفیت خروجی، زمان صرف‌شده و بخش‌های نیازمند اصلاح</strong> را با روش قبلی مقایسه کنیم.</div>`},
  {id:'toolbox', title:'فهرست ابزارها و لینک شروع', kicker:'TOOLBOX / QUICK REFERENCE', render:()=>`${heading('مرجع ابزارها؛ <span class="accent">برای استفاده بعد از جلسه.</span>', 'دسته را انتخاب کنید؛ لینک رسمی، روش شروع و نمونه درخواست هر ابزار در دسترس است.')}<div id="toolbox-filters" class="filters"></div><div id="toolbox-tools"></div>`},
  {id:'discussion', title:'تجربه‌های کاری همکاران', kicker:'TEAM EXPERIENCE', render:()=>`${heading('چه تجربه‌ای <span class="accent">ارزش انتقال به تیم دارد؟</span>', 'یک ابزار یا Workflow واقعی، مسئله‌ای که حل کرده و چیزی که از آن یاد گرفته‌اید.')}<form id="discussion-form"><div class="discussion-form"><label>ابزار یا Workflow<input name="tool" placeholder="مثلاً Codera یا n8n + AI" required maxlength="60"></label><label>مسئله کاری<input name="purpose" placeholder="چه کاری را انجام دادید؟" required maxlength="120"></label><label>نتیجه و ارزش<textarea name="reason" rows="2" maxlength="180" placeholder="کیفیت، زمان یا تجربه استفاده چگونه تغییر کرد؟"></textarea></label><label>محدودیت یا نکته قابل انتقال<textarea name="tip" rows="2" maxlength="180" placeholder="چه چیزی به اصلاح نیاز داشت؟"></textarea></label></div><div class="discussion-bottom"><button class="primary" type="submit">ثبت در یادداشت جلسه +</button><span class="muted" style="font-size:11px">فقط در حافظه همین صفحه؛ بدون ارسال به سرور.</span></div></form><div id="discussion-board" class="discussion-board" aria-live="polite"></div>`},
  {id:'closing', title:'قدم بعدی و AI Club', kicker:'AI CLUB / NEXT STEP', render:()=>`<div class="end-section">${heading('AI فقط <span class="accent">Chatbot</span> نیست.', 'کاربرد مهم‌تر از تعداد ابزارهایی است که می‌شناسیم.')}<h3 style="font-size:24px;margin:20px 0">یک قابلیت را در یک کار واقعی امتحان کنیم.</h3><div class="equation"><span>Your Tools</span><b>+</b><span>Your Workflows</span><b>+</b><span>Your Experiences</span></div><div class="club-wordmark">AI CLUB</div><p class="muted" style="margin-top:20px">تجربه‌های ما، ابزارها را به روش‌های قابل استفاده برای تیم تبدیل می‌کنند.</p><h3 class="accent" style="margin-top:13px">جلسه بعد: یک تجربه واقعی و یک Workflow قابل تکرار.</h3><button data-home style="margin-top:24px">نمای کلی ارائه ↗</button></div>`}
];
